### ISSUE TITLE
Razor PDF Download Sample Issue

### ISSUE THREAD

**Issue by saurabhrajput142** [RazorAnt/RazorPDFSample#1]
After download the sample project i see there is no .sln file project is missing into directory project is not able to run.
can you please send a running copy.
and also the css and images are not working for me.

Thanks & Regard

**Comment by RazorAnt** [comment]
If you clone the whole thing, you'll get the .sln file too.  It is in the root of the project.

[See here](https://github.com/RazorAnt/RazorPDFSample)
